// <auto-generated/>
#pragma warning disable CS0618
using FamMan.Clients.Chores.Item;
using FamMan.Clients.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace FamMan.Clients.Chores
{
  /// <summary>
  /// Builds and executes requests for operations under \chores
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class ChoresRequestBuilder : BaseRequestBuilder
  {
    /// <summary>Gets an item from the FamMan.Clients.chores.item collection</summary>
    /// <param name="position">key: id of chore</param>
    /// <returns>A <see cref="global::FamMan.Clients.Chores.Item.ChoreItemRequestBuilder"/></returns>
    public global::FamMan.Clients.Chores.Item.ChoreItemRequestBuilder this[Guid position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("chore%2Did", position);
        return new global::FamMan.Clients.Chores.Item.ChoreItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>Gets an item from the FamMan.Clients.chores.item collection</summary>
    /// <param name="position">key: id of chore</param>
    /// <returns>A <see cref="global::FamMan.Clients.Chores.Item.ChoreItemRequestBuilder"/></returns>
    [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
    public global::FamMan.Clients.Chores.Item.ChoreItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("chore%2Did", position);
        return new global::FamMan.Clients.Chores.Item.ChoreItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::FamMan.Clients.Chores.ChoresRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ChoresRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/chores", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::FamMan.Clients.Chores.ChoresRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ChoresRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/chores", rawUrl)
    {
    }
    /// <summary>
    /// Get all chores
    /// </summary>
    /// <returns>A List&lt;global::FamMan.Clients.Models.Chore&gt;</returns>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<List<global::FamMan.Clients.Models.Chore>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
        public async Task<List<global::FamMan.Clients.Models.Chore>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
      var requestInfo = ToGetRequestInformation(requestConfiguration);
      var collectionResult = await RequestAdapter.SendCollectionAsync<global::FamMan.Clients.Models.Chore>(requestInfo, global::FamMan.Clients.Models.Chore.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
      return collectionResult?.AsList();
    }
    /// <summary>
    /// Create a chore
    /// </summary>
    /// <returns>A <see cref="global::FamMan.Clients.Models.Chore"/></returns>
    /// <param name="body">The request body</param>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::FamMan.Clients.Models.Chore?> PostAsync(global::FamMan.Clients.Models.Chore body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
        public async Task<global::FamMan.Clients.Models.Chore> PostAsync(global::FamMan.Clients.Models.Chore body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
      if (ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
      var requestInfo = ToPostRequestInformation(body, requestConfiguration);
      return await RequestAdapter.SendAsync<global::FamMan.Clients.Models.Chore>(requestInfo, global::FamMan.Clients.Models.Chore.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Get all chores
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
      var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      return requestInfo;
    }
    /// <summary>
    /// Create a chore
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="body">The request body</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToPostRequestInformation(global::FamMan.Clients.Models.Chore body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::FamMan.Clients.Models.Chore body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
      if (ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
      var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
      return requestInfo;
    }
    /// <summary>
    /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
    /// </summary>
    /// <returns>A <see cref="global::FamMan.Clients.Chores.ChoresRequestBuilder"/></returns>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    public global::FamMan.Clients.Chores.ChoresRequestBuilder WithUrl(string rawUrl)
    {
      return new global::FamMan.Clients.Chores.ChoresRequestBuilder(rawUrl, RequestAdapter);
    }
    /// <summary>
    /// Configuration for the request such as headers, query parameters, and middleware options.
    /// </summary>
    [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChoresRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
    {
    }
    /// <summary>
    /// Configuration for the request such as headers, query parameters, and middleware options.
    /// </summary>
    [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChoresRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
    {
    }
  }
}
#pragma warning restore CS0618
