// <auto-generated/>
#pragma warning disable CS0618
using FamMan.Clients.Events;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace FamMan.Clients
{
  /// <summary>
  /// The main entry point of the SDK, exposes the configuration and the fluent API.
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class EventsClient : BaseRequestBuilder
  {
    /// <summary>The events property</summary>
    public global::FamMan.Clients.Events.EventsRequestBuilder Events
    {
      get => new global::FamMan.Clients.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>
    /// Instantiates a new <see cref="global::FamMan.Clients.EventsClient"/> and sets the default values.
    /// </summary>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public EventsClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
    {
      ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
      ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
      ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
      ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
      ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
      ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
      ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
      if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
      {
        RequestAdapter.BaseUrl = "localhost:7038";
      }
      PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
    }
  }
}
#pragma warning restore CS0618
