openapi: '3.0.2'
info:
  title: Events
servers:
  - url: localhost:7038

components:
  schemas:
    event:
      type: object
      properties:
        Id:
          type: string
          format: uuid
        Name:
          type: string
        EventType:
          type: string
        Description:
          type: string
        RecurrenceRules:
          type: object
          additionalProperties: true
        IsActive:
          type: boolean
        CreatedAt:
          type: string
          format: date-time
        UpdatedAt:
          type: string
          format: date-time
  parameters:
    event-id:
      name: event-id
      in: path
      description: 'key: id of event'
      required: true
      style: simple
      schema:
        type: string
        format: uuid

paths:
  /events:
    get:
      description: Get all events
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/event'
    post:
      description: 'Create an event'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/event'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'
  /events/{event-id}:
    get:
      description: 'Get event by ID'
      parameters:
      - $ref: '#/components/parameters/event-id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'
    put:
      description: 'Update post'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/event'
      parameters:
      - $ref: '#/components/parameters/event-id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'
    delete:
      description: 'Delete event'
      parameters:
      - $ref: '#/components/parameters/event-id'
      responses:
        '200':
          description: OK